#opérations Aritharithmétiques
print( "2. Opération Aritharithmétiques avec 3 et 4")
print( "Addition")
print(" 3 + 4 = ",3+4)
print( "Soustraction")
print(" 3 -  4 = ",3-1)
print( "Multiplication")
print(" 3 X 4 = ",3*4)
print( "Division")
print(" 3 / 4 = ",4/3)
print( "Modulo")
print(" 3 % 4 = ",3%4)
print( "Puissance")
print(" 3 ** 4 = ",3**4)   
print( "Division entière")
print(" 3 // 4 = ",3//4)
print( "")

#affichage de chaine de caractères
print( "3. Affichage chaine de caractères")
print("Nom: Daniel")
print("Prénom: François")
print("Pays: Bénin")
print("Langue: Français")
print("je profite de 30 jours de python pour renforcer mes compétences en python")
print( "")

#types de données
print( "4. Types de données")
print("Type de 3 est ", type(3))
print("Type de 3.14 est ", type(3.14))
print("Type de 3 + 4j est ",type(3 + 4j))
print("Type de <Hello> est ", type("Hello"))
print("Type de [1, 2, 3] est ", type([1, 2, 3]))
print("Type de (1, 2, 3) est ", type((1, 2, 3)))
print("Type de {1, 2, 3} est ", type({1, 2, 3}))
print("Type de {\"a\": 1, \"b\": 2} est ", type({"a": 1, "b": 2}))
print("Type de True est ", type(True))

